services:

  db:
    image: postgres:17.4
    env_file: ".env.example"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data



  secop-service:
    image: ghcr.io/bilchreis/secop_service:0.0.17
    restart: always
    env_file: ".env.example"
    ports:
      - 4001:4001
    depends_on:
      - db
